apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-up-backend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: next-up-backend
  template:
    metadata:
      labels:
        app: next-up-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: next-up-secrets
            - configMapRef:
                name: next-up-config