apiVersion: v1
kind: Service
metadata:
  name: next-up-backend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: next-up-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}