# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#   name: next-up-backend-vpa
#   namespace: {{ .Release.Namespace }}
# spec:
#   targetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: next-up-backend-deployment
#   updatePolicy:
#     updateMode: "Auto"
#   resourcePolicy:
#     containerPolicies:
#       - containerName: backend
#         controlledResources:
#           - cpu
#           - memory
#
# ---
#
# apiVersion: autoscaling.k8s.io/v1
# kind: VerticalPodAutoscaler
# metadata:
#   name: next-up-frontend-vpa
#   namespace: {{ .Release.Namespace }}
# spec:
#   targetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: next-up-frontend-deployment
#   updatePolicy:
#     updateMode: "Auto"
#   resourcePolicy:
#     containerPolicies:
#       - containerName: frontend
#         controlledResources:
#           - cpu
#           - memory