apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-up-frontend-deployment
  namespace: next-up
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-up-frontend
  template:
    metadata:
      labels:
        app: next-up-frontend
    spec:
      containers:
        - name: frontend
          image: next-up-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
